### ISSUE TITLE
[TypeError]When I save *.xls code give an  TypeError

### ISSUE THREAD

**Issue by BrightSoulXYHY** [python-excel/xlutils#11]
Hello, I want to appendix some thing to *.xls remainding file formatting

the code is

from xlutils.copy import copy 
from xlrd import open_workbook 
file_path = "book1.xls"
rb = open_workbook(file_path, formatting_info=True)
# a writable copy (I can't read values out of this, only write to it)
wb = copy(rb) 
w_sheet = wb.get_sheet(0)
w_sheet.write(0,0,"foo")
wb.save('book2.xls')

the log info is

Traceback (most recent call last):
  File "F:\Progroming\Python\_Temp\temp.py", line 21, in <module>
    wb.save('book2.xls')
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\Workbook.py", line 710, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\Workbook.py", line 667, in get_biff_data
    before += self.__all_fonts_num_formats_xf_styles_rec()
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\Workbook.py", line 570, in __all_fonts_num_formats_xf_styles_rec
    return self.__styles.get_biff_data()
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\Style.py", line 185, in get_biff_data
    result += self._all_num_formats()
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\Style.py", line 209, in _all_num_formats
    result += NumberFormatRecord(fmtidx, fmtstr).get()
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\BIFFRecords.py", line 785, in __init__
    ufmtstr = upack2(fmtstr)
  File "D:\SoftWare\Anaconda3\lib\site-packages\xlwt\UnicodeUtils.py", line 50, in upack2
    us = unicode(s, encoding)
TypeError: descriptor 'decode' requires a 'bytes' object but received a 'NoneType'

**Comment by yejunzhou** [comment]
set “s” default “General” work fine
```python
def upack2(s, encoding='ascii'):
    # If not unicode, make it so.
    if isinstance(s, unicode_type):
        us = s
    else:
        if s is None:
            us = 'General'
        else:
            us = unicode(s, encoding)
```

**Comment by TimMieto** [comment]
> set “s” default “General” work fine
> 
> ```python
> def upack2(s, encoding='ascii'):
>     # If not unicode, make it so.
>     if isinstance(s, unicode_type):
>         us = s
>     else:
>         if s is None:
>             us = 'General'
>         else:
>             us = unicode(s, encoding)
> ```

Thank you for your reply. It solved my problem.
However it did took much time for me on confusing where to apply this method...
Finally I found this method in  \venv\Lib\site-packages\xlwt\UnicodeUtils.py
